### ISSUE TITLE
Popup doesn't wait for next input

### ISSUE THREAD

**Issue by eltone** [TheBlob42/idea-which-key#1]
Rider 20.3.2, idea-vim 0.65, idea which-key 0.2, with the intellimacs config

My which-key popup appears for half a second on the first input, then disappears. I would expect it to remain until I press the final input in the chain or ESC.

<details>
<summary>.ideavimrc:</summary>

```
""" Map leader to space ---------------------
let mapleader=" "
let maplocalLeader=" "

""" Plugins  --------------------------------
set surround
set multiple-cursors
set commentary
set argtextobj
set easymotion
set textobj-entire
set ReplaceWithRegister
set which-key

""" Plugin settings -------------------------
let g:argtextobj_pairs="[:],(:),<:>"

""" Common settings -------------------------
set showmode
set so=5
set incsearch
set nu

""" Idea specific settings ------------------
set ideajoin
set ideastatusicon=gray
set idearefactormode=keep

""" Mappings --------------------------------
""" map <leader>f <Plug>(easymotion-s)
""" map <leader>e <Plug>(easymotion-f)

map <leader>d :action Debug<CR>
map <leader>r :action RenameElement<CR>
map <leader>c :action Stop<CR>
map <leader>z :action ToggleDistractionFreeMode<CR>

map <leader>s :action SelectInProjectView<CR>
map <leader>a :action Annotate<CR>
map <leader>h :action Vcs.ShowTabbedFileHistory<CR>
map <S-Space> :action GotoNextError<CR>

map <leader>b :action ToggleLineBreakpoint<CR>
map <leader>o :action FileStructurePopup<CR>
imap fd <Esc>

" Selected Intellimacs modules
source ~/.intellimacs/spacemacs.vim
source ~/.intellimacs/extra.vim
source ~/.intellimacs/major.vim

" Comma for major mode
nmap , <leader>m
vmap , <leader>m
```
</details>

**Comment by TheBlob42** [comment]
Hey @eltone I just checked your `.ideavimrc` and realized that I have forgotten to document two of IdeaVIMs options that are quite relevant for the plugin :sweat_smile: 

By default IdeaVIM will wait one second after you have pressed a key that is part of a mapping sequence. If you don't follow up the key press with another one continuing or completing the sequence within this time IdeaVIM will cancel the sequence and will instead execute the default actions for each key press one after another (if there are any).

For example: 
If you have a mapping `dwe` and press `dw` shortly after another, but then pause for over a second IdeaVIM will not wait any longer and cancel the sequence. Then it will execute the default actions for both key presses after another which in this case will delete the next word. 

To solve your issue you can either increase the timeout or completely disable this feature in your `.ideavimrc`:

```vim
" increase the timeout period (in milliseconds)
set timeoutlen=10000
" completely disable the feature
set notimeout
```

So to get the behavior you wish I would probably go with the `notimeout` option.

I will definitively add some documentation about this to the `README`. Thanks for pointing this out :+1:

**Comment by macintacos** [comment]
@TheBlob42 I'm running into the same thing, but setting those options doesn't quite work for me. Increasing the timeout increases the time that I have to perform the chord, however it doesn't actually increase the time that the popup is shown at the bottom of the UI. The UI goes away just as quickly, regardless of how I have it setup.

FWIW, I use Intellimacs along with some nominal remappings, but I don't really think that there's anything that I have setup that's governing this behavior. Here's my `.ideavimrc`:

```vim
" Leader (this needs to be done before we set easymotion)
let mapleader = " "

" Options
set NERDTree
set ReplaceWithRegister
set clipboard+=unnamed
set commentary
set easymotion
set highlightedyank
set hlsearch
set ideajoin
set ideamarks
set ignorecase
set multiple-cursors
set number
set relativenumber
set showmode
set smartcase
set surround
set which-key

set timeoutlen=10000

" Selected Intellimacs Modules
source ~/.intellimacs/spacemacs.vim
source ~/.intellimacs/extra.vim
source ~/.intellimacs/major.vim
source ~/.intellimacs/hybrid.vim

" remaps
inoremap jj <Esc>
inoremap kk <Esc>

nnoremap gD        :action SmartSearchAction<CR>
nnoremap gh        :action QuickImplementations<CR>
nnoremap <space>jl :action AceLineAction<CR>
nnoremap <space>jw :action AceWordAction<CR>
nnoremap <space>jv :action AceTargetAction<CR>
nnoremap f         :action AceWordForwardAction<CR>
nnoremap F         :action AceWordBackwardsAction<CR>
nnoremap J         :action MoveLineDown<CR>
vnoremap J         :action MoveLineDown<CR>
nnoremap K         :action MoveLineUp<CR>
vnoremap K         :action MoveLineUp<CR>
nnoremap <C-j>     :action EditorCloneCaretBelow<CR>
nnoremap <C-k>     :action EditorCloneCaretAbove<CR>
nnoremap <A-j>     :action EditorDuplicateLines<CR>
vnoremap <A-j>     :action EditorDuplicateLines<CR>
nnoremap gb        :action SelectNextOccurrence<CR>
nnoremap <C-n>     :action SelectNextOccurrence<CR>
nnoremap gB        :action SelectAllOccurrences<CR>
vnoremap gb        :action SelectNextOccurrence<CR>
vnoremap <C-n>     :action SelectNextOccurrence<CR>
vnoremap gB        :action SelectAllOccurrences<CR>
nnoreap <C-s>      :action SaveAll<CR>:action ReformatCode<CR>

" Blackhole everything, make a 'move'
nnoremap d "_d
nnoremap dd "_dd
nnoremap D "_D
nnoremap c "_c
nnoremap C "_C
nnoremap x "_x
nnoremap X "_X
nnoremap m d
vnoremap m d
nnoremap mm d
nnoremap M D

" Jumping to symbols and stuff, in current file and across project
nnoremap <leader>ji :action FileStructurePopup<CR>
vnoremap <leader>ji :action FileStructurePopup<CR>
nnoremap <leader>jI :action GotoSymbol<CR>
vnoremap <leader>jI :action GotoSymbol<CR>
nnoremap <leader>jr :action FindUsages<CR>

" Focus next window
nnoremap <leader>w<TAB> :action NextSplitter<CR>
vnoremap <leader>w<TAB> <Esc>:action NextSplitter<CR>

" Formatting code
nnoremap <leader>f= :action ReformatCode<CR>
vnoremap <leader>f= :action ReformatCode<CR>

" Restarting
nnoremap <leader>feR :action InvalidateCaches<CR>

" NERDTree Remaps
let g:NERDTreeMapActivateNode='l'
let g:NERDTreeMapOpenRecursively='L'
let g:NERDTreeMapCloseDir='h'
let g:NERDTreeMapCloseChildren='H'
```

**Comment by TheBlob42** [comment]
Hey @macintacos I have just tested it with your `.ideavimrc` (including intellimacs) and for me the increased `timeoutlen` setting works as it should :thinking: 

Did you reload your `.ideavimrc` from within Intellij or did you also tried a restart of the IDE?
It seem with the latest update `0.65` that the reload mechanism does not work properly anymore.

Do you have any other IdeaVIM specific plugins installed? Maybe one of them is somehow interfering here (maybe one that I have not installed and is therefore not being activated by your `.ideavimrc` on my machine)

Waiting for your feedback :)

**Comment by macintacos** [comment]
I reloaded from within Intellij since I thought that would work, let me try a full-blown restart and get back to you.

**Comment by macintacos** [comment]
Yep, that was it! I guess `:source ~/.ideavimrc` isn't as reliable as I was led to believe 🙂 thanks!

**Comment by TheBlob42** [comment]
Glad to hear that it worked :slightly_smiling_face: 

It's weird, since the `:source ~/.ideavimrc` command definitively worked before I upgraded IdeaVIM to the latest version (I used it for my own testing), so I was as surprised as you when it was not behaving as expected anymore :see_no_evil: 

I will keep this issue open till I have adapted the documentation or if there are any further questions regarding this.

**Comment by TheBlob42** [comment]
Ok I have to take everything back, nothing is broken within IdeaVIM :see_no_evil: 
It's an issue in my code that the reload from within Intellij does not work properly. I will provide a fix for this.

**Comment by TheBlob42** [comment]
It seems that VIM options are only set from the `.ideavimrc` on startup and can be temporarily changed from within Intellij using the `:set ...` command. I am not 100% sure I understand this correctly, but there is no bug in IdeaVIM :slightly_smiling_face: 

Reloading your config with `:source ...` should otherwise work fine.
Sorry for the confusion.
