### ISSUE TITLE
Custom descriptions not being recognized

### ISSUE THREAD

**Issue by Craksy** [TheBlob42/idea-which-key#17]
I recently installed the extension and I simply can't make it pick up custom descriptions, or any of the other settings that are configured via global variables for that matter.

I've tried for different types of mappings, both leader and non-leader bindings. I've experimented with different ways of writing the values, like trying `<leader>`, `<Space>` and a litteral ` `.
I even tried using the _right hand side_ of the mapping as suggested in the README (although I assume that must've been a typo)
I've also removed most of my mappings, just in case there was something funky in there that would cause trouble when parsing. I also tried putting the declarations in different places.

However, since none of the other configuration variables, like `g:WhichKey_ShowVimActions` are being picked up either, I doubt it's about the way I've defined the descriptions.
I checked with `:echo g:WhichKeyDesc_...` and they are indeed being defined, they do just not seems to be recognized by Which-Key.

I'm using: 
JetBrains Rider 2021.2.1
IdeaVim 1.7.1
and Which-Key 0.5

```vim
let mapleader=" "

set surround
set commentary
set argtextobj
set easymotion
set textobj-entire
set NERDTree
set highlightedyank
set which-key

set scrolloff=5
set incsearch
set number relativenumber
set gdefault
set hlsearch
set ideajoin
set notimeout

let g:WhichKey_ShowVimActions = "true"
let g:WhichKey_ShowTypedSequence = "false"
let g:WhichKey_DefaultDelay = 60000

let g:WhichKeyDesc_find = "<Space>f     Find"
let g:WhichKeyDesc_find_usages = "<Space>fu     Find Usage"


imap jk <Esc>

map <leader>w <C-w>
map <C-w>q :q<cr>

map s <Plug>(easymotion-prefix)
map go <Action>(FileStructurePopup)

map <leader>; <Action>(GotoAction)

" files and find
map <leader>fs :w<cr>
map <leader>fp :e ~/.ideavimrc<cr>
map <leader>fu <Action>(FindUsages)
map <leader>ff <Action>(Find)


" go/git
map <leader>gu <Action>(ShowUsages)
map <leader>gg <Action>(ActivateVersionControlToolWindow)

" Toggles
map <leader>ta <Action>(Annotate)
map <leader>th <Action>(ToggleInlayHintsGloballyAction)
map <leader>tp <Action>(HideActiveWindow)
map <leader>ts <Action>(HideSideWindows)
map <leader>tt <Action>(HideAllWindows)

" Open
map <leader>op :NERDTreeToggle<cr>
map <leader>ot <Action>(ActivateTerminalToolWindow)

" Insert
map <leader>ii <Action>(Generate)
map <leader>is <Action>(InsertLiveSnippet)

" Help and utility
map <leader>he <Action>(ActivateEventLogToolWindow)
map <leader>hrR <Action>(RestartIde)
map <leader>hrr :so ~/.ideavimrc<cr>

" Tab nav
nnoremap <A-1> :tabn 1<cr>
nnoremap <A-2> :tabn 2<cr>
nnoremap <A-3> :tabn 3<cr>
nnoremap <A-4> :tabn 4<cr>
nnoremap <A-5> :tabn 5<cr>
```

Did I miss something really obvious?

**Comment by TheBlob42** [comment]
Hey @Craksy it seems you have either copied a wrong value for `g:WhichKey_DefaultDelay` or misunderstood the usage of this variable. Your config does work (at least on my setup), but the popup will only show up after 60000 ms (so after a minute of not pressing any key), which is probably not what you want

I would propose you either remove that line completely or reduce the value to a more reasonable value (the default is 200ms)  
Other than this I could not see any issue with your configuration.

Regarding the "using the right hand side" you are absolutely correct. This is a typo of mine and I will fix asap. Thank you for spotting it :+1: 

Let me know if I could help you with your problem or if you're still experiencing this or another issue with the plugin :slightly_smiling_face:

**Comment by Craksy** [comment]
Thanks for the quick reply @TheBlob42 ^^
Yeah, I should probably have clarified on that bit. This was a part of me troubleshooting to confirm that it does in fact not recognize the variables at all. It does have 200ms delay even with this set.
It also displays the typed sequence, and excludes vim actions despite those being set as well.

If it gives you any clue, I've noticed that Which-Key doesn't reload when sourcing the configuration. I can add or remove mappings and resource my .ideavimrc, but Which-Key seems to be locked in its initial state. Even disabling the plugin didn't take effect until I restarted the IDE. Even then, the `g:Global_Variables` are being ignored though.

I don't know if there's any additional info I can provide that could help narrow it down. I'm not really getting any errors and I just recently started transitioning to Rider, so I'm not all that familiar with the environment.
If there's anything you need, please let me know.

**Comment by TheBlob42** [comment]
Hmm ok that is indeed very weird :thinking:
 
I know that there have been some problems with "sourcing" the configuration, but I since I have not changed anything in the plugin regarding this, it might be related to an Intellij or IdeaVIM update, therefore always restart in order to be sure that everything is being sourced correctly. Maybe I can find out something more regarding this "different" issue.

I am currently on a train, but when I have time (and a better internet connection) I will try to update everything and see if maybe a Jetbrains or IdeaVIM update broke anything, which could explain your problem.

If you have the time you might try your configuration with Intellij Community (this is the only IDE I have access to) and see if this might be a specific issue with Rider.

I will get back to you soon :slightly_smiling_face:

**Comment by TheBlob42** [comment]
Ok I just updated to the newest IdeaVIM version (`1.7.1`) and have the same problem now :slightly_frowning_face: 
I don't have a clue yet what has changed which would affect the pick up of the global variables, need to investigate...

You could manually revert to an older version of IdeaVIM to make it work, but I am not sure if this is worth the effort  
Otherwise you have to wait for a fix here, but since the custom values are present (as seen with `:echo g:WhichKey...`) I hope that this will not be a big issue

**Comment by lippfi** [comment]
@TheBlob42  oops, sorry, `VimScriptGlobalEnvironment` seems to be broken. It will be fixed this week in IdeaVim version 1.7.2.
Feel free to create issues on Youtrack (https://youtrack.jetbrains.com/issues/VIM)
Have a nice day!

**Comment by TheBlob42** [comment]
@lippfi thank you for the response and that you pointed out this error, this saves me probably quite some time of testing and debugging. Are you already tackling this issue regarding `VimScriptGlobalEnvironment` or should I (still) open a ticket for it?

**Comment by lippfi** [comment]
@TheBlob42 this issue is a part of 1.7.2 bugfix release, ticket is not needed

**Comment by TheBlob42** [comment]
@Craksy I just updated to IdeaVim `1.7.2` and now everything works fine for me again. Please update and check your if your setup is now working.

**Comment by Craksy** [comment]
> @Craksy I just updated to IdeaVim `1.7.2` and now everything works fine for me again. Please update and check your if your setup is now working.

I just set up my configuration on a new machine and everything seems to work as intended. I think it's pretty safe to assume that it was about the IdeaVim version though.

Thanks a lot for the help figuring this out! My environment is definitely going to feel more like home with Which-Key working properly ^^
