### ISSUE TITLE
VimShortcutKeyAction Problem is back

### ISSUE THREAD

**Issue by rayk** [TheBlob42/idea-which-key#20]
On startup the following appears.

This is happening on
IntelliJ IDEA 2021.3 (Ultimate Edition)

java.lang.Throwable: ID "VimShortcutKeyAction" is already taken by action "null (null)". Action "null (null)" cannot use the same ID null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1300)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1236)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1309)
	at eu.theblob42.idea.whichkey.WhichKeyExtension$init$1.run(WhichKeyExtension.kt:42)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by TheBlob42** [comment]
Can confirm that this is happening :thinking:  strangely on my machine it does not occur with the community edition, but only with ultimate (can't test with any other Jetbrains IDE) will investigate

**Comment by TheBlob42** [comment]
Ok I could solve it by updating the dependency, but I am not 100% sure that this is "the" solution.
But regarding the just revealed log4j security vulnerability it probably makes sense to update these libs anyway :slightly_smiling_face: 
You can install the new version `0.6.1` manually or wait for the marketplace release

**Comment by GreenHapi** [comment]
Just updated to 0.6.1 and bug still persists.
JetBrains Rider 2021.3.1

**Comment by TheBlob42** [comment]
Can you answer me the following questions:
- Which version of the IdeaVim plugin do you have installed?
- Does the plugin work in general? Despite the error on startup

The last release triggered some compatibility issues: `Compatible. 3 usages of scheduled for removal API`, but I doubt that this can be the reason. Also I see this warning in the JetBrains checks, so maybe it has something to do with rider? But again I am not certain that this is really the issue here...

```
(failed) (optional) module com.intellij.modules.rider: Plugins declaring module 'com.intellij.modules.rider' are not found in Marketplace https://plugins.jetbrains.com
```

Well, I am gonna continue investigating, but I am always happy for ideas :detective: 

@rayk can you check if the latest version fixes the issue for you? :thinking:

**Comment by rayk** [comment]
@TheBlob42 here is what I can observe.

1. I have version 0.6.1 installed from the JetBrains store
2. Besides the exception at the start, the plug appears to be working.

I say appears to be working, the only problem I have noticed (It is probably related to my config) is the command buffer get stuck.

1. I hit the lead key, Which key appears.
2. I hit a key or key sequence that is not mapped, Which keys diappears I get the beep. and key sequences continue to accumulate in the buffer. I can see this as it builds up in the bottom status bar. Esc , extra does not stop it listening, and it never timeouts.

**My Config for reference** 

```
""" Plugin Settings: Which Key Config --------------------------
set notimeout
set timeoutlen = 4000


let g:WhichKey_SortOrder = "by_description"
let g:WhichKey_ShowVimActions = "true"

let g:WhichKeyDesc_move_top = "gg   Move to first line"

let g:WhichKeyDesc_move_back_end = "ge   Move Back to previous end"

let g:WhichKeyDesc_next_tab = "gt   Tab (Focus On Next)"

let g:WhichKeyDesc_previous_tab = "gT   Tab (Focus On Previous)"

let g:WhichKeyDesc_goto_define = "gd   Definition Of ~ In new tab"
let g:WhichKeyDesc_get_ascii = "ga   Ascii ~ Get Value"
```

**Comment by TheBlob42** [comment]
> 1. I have version 0.6.1 installed from the JetBrains store

I was actually referring to the version for the [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim) plugin since WhichKey is built upon it :slightly_smiling_face: current version should be `1.9.1`

> I say appears to be working, the only problem I have noticed (It could be related to my config) is the command buffer is getting stuck.
> 
>   1. I hit the leader key or g, Which key appears, as expected.
> 
>   2. I hit a key or key sequence that is not mapped, Which keys disappears and I get a beep. But key sequences continues to accumulate in the buffer. I can see this as it builds up in the bottom status bar. Esc , extra does not stop it listening, and it never timeouts. I have to close the tab and reopen it before Which-key returns to normal operations.

Sorry, but I can not replicate this behavior at all and I am not sure that I understand correctly what you mean :thinking: could please share maybe a recording of the behavior you're facing and your complete config (as it seems you have only shared the part about which-key). I suspect this has something to do with another mapping or plugin, but I need more information for this

> BTW keep up the good work, Coming back to Vim after being away for far too long, I have come to depend on which-key.

Thank you :heart: glad to hear that it helps people

**Comment by rayk** [comment]
Yep totally missed that, my current version of ideavim s 1.9.1.

I will create another issue for the above behaviour...

**Comment by TheBlob42** [comment]
I have just uploaded a new version `0.6.2` with another attempt to fix the issue
You can either try it out by installing it manually or wait for 1-2 days till it gets approved by JetBrains and you can download the update via the Marketplace

> I will create another issue for the above behaviour...

Thank you :+1: this is most probably another problem

**Comment by GreenHapi** [comment]
I have IdeaVim 1.9.1 as well.
0.6.2 fixed issue for me. Thank you!

**Comment by rayk** [comment]
It is fixed with 0.6.2. Happy if this closed.

**Comment by TheBlob42** [comment]
Glad to hear :slightly_smiling_face:

**Comment by rayk** [comment]
hey, @TheBlob42 here is a clue: just installed the update for the [plantUML](https://plugins.jetbrains.com/plugin/7017-plantuml-integration) plugin and it trigged the same problem as above. 

Upon removing the PlantUML plugin, all is well. I have dumped the plugin, so I do not have any issues with which key. No action is required for me, hope this offer a clue as to the root cause.

Thanks again

**Comment by TheBlob42** [comment]
Glad to hear that you found a "workaround" even though it means to remove another plugin.
I have had a quick look and installed the plugin, but strangely I can not reproduce it and from a quick glance at their source code I have no idea unfortunately :sweat_smile:
