### ISSUE TITLE
Useage under windows

### ISSUE THREAD

**Issue by BroodingMawlek** [TheBlob42/idea-which-key#23]
Hi, installed the plugin and added 

C:\Users\user\.ideavimrc
set which-key
set notimeout

Hitting space to activate and nothing happens. Sorry not familiar with which-key.

**Comment by TheBlob42** [comment]
Do you have the [IdeaVim](https://github.com/JetBrains/ideavim) plugin installed? This plugin does not work without it.
Did you create the `.ideavimrc` file in the correct place? Under Windows it should be in `C:\Users\<your username>\.ideavimrc` (maybe its just a typo in your example).

See  on the plugin page under [files](https://github.com/JetBrains/ideavim#files) for more information.

Otherwise from the information you have provided I don't see anything wrong with the files content :thinking: 
Please let me know if one the above suggestions helped you

**Comment by BroodingMawlek** [comment]
IdeaVim is installed
yes, that was a typo file is C:\Users\<your username\.ideavimrc
File is below,  IdeaVim is working fine, I just press space to invoke which-key, right ?

Thanks for taking the time to answer.
.......................
"" config https://github.com/TheBlob43/idea-which-key
set which-key
set notimeout

"" Source your .vimrc
"source ~/.vimrc
"" -- Suggested options --
" Show a few lines of context around the cursor. Note that this makes the
" text scroll if you mouse-click near the start or end of the window.
set scrolloff=5

" Do incremental searching.
set incsearch

" Don't use Ex mode, use Q for formatting.
map Q gq


"" -- Map IDE actions to IdeaVim -- https://jb.gg/abva4t
"" Map \r to the Reformat Code action
"map \r <Action>(ReformatCode)

"" Map <leader>d to start debug
"map <leader>d <Action>(Debug)

"" Map \b to toggle the breakpoint on the current line
"map \b <Action>(ToggleLineBreakpoint)


" Find more examples here: https://jb.gg/share-ideavimrc


.......................

**Comment by TheBlob42** [comment]
Well if I see that correct, than you are not defining any mappings longer than a single keystroke in your `.ideavimrc` file :thinking: 

`which-key` will only activate for mappings which take multiple keystrokes. The GIF in the readme file is just an example for how it could look if you have multiple mappings activated. The example uses the mappings from [intellimacs](https://github.com/MarcoIeni/intellimacs) which defines a whole lot of "Spacemacs" like keybindings for you. Give it a try as it is a really good configuration.

Try it with the following minimal example `.ideavimrc` file:
```vim
set which-key
set notimeout
nnoremap <Space>ff :action GotoFile<CR>
nnoremap <Space>fr :action RecentFiles<CR>
```
Now if you press space you should see a small popup window, showing you that `f` is a prefix key: 

![image](https://user-images.githubusercontent.com/6849129/162628592-eff17943-084f-436f-8a7a-a1fd5ac64b57.png)

And if you hit `f` afterwards you should see a small popup window showing you the two options about opening a file or a recent file.

![image](https://user-images.githubusercontent.com/6849129/162628578-e2e0567b-2991-45fb-bf3a-af238785b3b0.png)

I hope this helps you :slightly_smiling_face: let me know if the minimal example worked

**Comment by BroodingMawlek** [comment]
That works perfectly, thanks for taking the time to help me out, really appreciate it!

**Comment by TheBlob42** [comment]
No problem :+1: I am always happy to help
