### ISSUE TITLE
Can we use which Key without ideavim?

### ISSUE THREAD

**Issue by AlgusDark** [TheBlob42/idea-which-key#25]
Like the title says. I'm a new user of intelliJ and I use keyboard chords in vscode. I would love to to do that but with this table showing the hints that can go into a deeper level.

Thanks!

**Comment by TheBlob42** [comment]
No that is unfortunately not possible :slightly_frowning_face: 

WhichKey is written as an extension specifically for IdeaVim and is therefore extremely entwined with it (for example loading the `.ideavimrc` file, getting all available mappings, getting the current "mapping state" etc.)
