### ISSUE TITLE
[enhancement]Don't process key press if it's not a valid mapping sequence

### ISSUE THREAD

**Issue by yejianfengblue** [TheBlob42/idea-which-key#32]
The idea-which-key readme says
> By default (Idea)VIM will wait for timeoutlen milliseconds after each key press of any unfinished mapping sequence before it cancels the whole sequence and **processes each key press individually one after another.** 

If I press an invalid mapping sequence such as `<space>k`, I want the whole key press to be ignored instead of being processed individually. Because I have to take additional effort to fix the key press mistake. 
Can it be achieved in the idea-which-key plugin? Or impossible due to the ideavim limitation? 

For example, `<space>k` is NOT a mapping sequence and I press `<space>` and `k` by mistake, then the key press `<space>` and `k` are processed individually, which causes the cursor move right and up. To fix this, I have to move the cursor back to the original position.

Another example, `<space>p` is NOT a mapping sequence and I press `<space>` and `p` by mistake, then the key press `<space>` and `p` are processed individually, which causes the cursor move right and the clipboard content pasted. To fix this, I have to press `u` to undo and move the cursor back to the original position.

**Comment by TheBlob42** [comment]
Hey @yejianfengblue, thanks for the suggestion. I can fully understand the inconvenience this behavior is causing for you. I am quite sure that this can be addressed and I will have a look into it to see what I can do.

**Comment by TheBlob42** [comment]
Sorry for the long silence here :frowning_face: 

Bad news: I did not have that much time in the last weeks to look into this
Good news: I have a working solution and "just" need to clean everything up, prepare a release & test a bit, but I'll probably need a few more days to finish all of this

**Comment by yejianfengblue** [comment]
Many thanks for your effort. Not urgent. Take your time.

**Comment by TheBlob42** [comment]
I have encountered some "issues" with operator mappings that need some time to solve them properly

Say you have the [surround](https://github.com/JetBrains/ideavim/wiki/IdeaVim-Plugins#surround) plugin activated you'll get a new mapping on `ds`. Pressing `d` will show the popup with one element. But even though they are not "real" mappings but rather built in actions you still want delete motions like `dj`, `dip` etc. to work and not be blocked. This is a little more complicated then I thought, but I am confident that it is manageable. 

I''ll add new changes to the `develop` branch first in case you want to test the latest version by building the plugin yourself

**Comment by TheBlob42** [comment]
I have committed the latest changes to the `develop` branch. Will test it a bit to find more possible edge cases. Would be glad if you could build it locally and give it a test as well :slightly_smiling_face:

**Comment by yejianfengblue** [comment]
Thanks for your working. In my first test, the `<space> k` and `<space> p` issues in my issue description are fixed.

Unfortunatily, I have a habit to use `<Esc>` to cancel a which-key mapping sequence in Emacs, and it's known that the `<Esc>` can't be intercepted. Anyway, you have done a good job.

**Comment by TheBlob42** [comment]
Yeah the thing with modified and special keys is still bugging me, but I did not have the time to find a solution for this yet :frowning_face: 

I will also continue testing a little longer for possible edge cases that are not covered yet and if everything is fine prepare a release the next week

**Comment by TheBlob42** [comment]
Version `0.8.0` has been released on Github.
On the marketplace it will take a little longer due to pre-checks by Jetbrains

**Comment by luqasn** [comment]
Hey, does this really belong into in which-key? it doesn't really have to do anything with it as far as I can see.
This is just the normal behaviour of (neo|idea)vim, whether you enable which-key or not.

**Comment by yejianfengblue** [comment]
> Hey, does this really belong into in which-key? it doesn't really have to do anything with it as far as I can see. This is just the normal behaviour of (neo|idea)vim, whether you enable which-key or not.

Yes. The author add an option to solve my problem. https://github.com/TheBlob42/idea-which-key#on-unknown-mapping

**Comment by luqasn** [comment]
Yes, I meant to say I don't think it should really be part of which-key.

I am not saying you wanting this is unreasonable, I am just saying it doesn't really have anything to do with which-key if you want to change how vim multi-key commands work.

Do you think your needs would also be solved if ESC was properly supported (close which-key window without action) and you put `map <leader>k <nop>`, `map <leader>p <nop>` (and also for you other "unmapped" sequences) in your config?

I am asking because this is a complex piece of code and it is very hard to get it right for all edge cases, which leads to bugs like this: https://youtrack.jetbrains.com/issue/VIM-3193/vim-exchanges-cxmotion-does-not-work-with-WhichKeys-option-gWhichKeyProcessUnknownMappings-set-to-false

Please also note that I am not the author, I've just started contributing
