### ISSUE TITLE
which-key hinders execution of command

### ISSUE THREAD

**Issue by ronnac** [TheBlob42/idea-which-key#33]
Situation:
I have mapped daf (delete-a-function) to delete a Python function. This works fine, but now, whenever I press d in normal or visual mode, which-key pops up, even when it doesn't make sense:
1) visual selection + d should delete the selected text, however, which-key waits for more input. I have to press ESC to execute the deletion

2) dd in normal mode should delete a line. Again, I need to press ESC.

**Comment by TheBlob42** [comment]
I don't have the problem you're describing at all, therefore I think it could be something in regards to your configuration :thinking: could you share your `ideavimrc` file so I can take a look?

**Comment by ronnac** [comment]
Here is a minimal example, tested on both PyCharm 2021.3 Pro (IdeaVim 1.10.3) and 2022.2.4 Community (IdeaVim 1.11.1)
"""""""""""""""""""""""""""""""""""""""""""""""""""" Plugins """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" Which key
set which-key
set notimeout
Plug 'michaeljsmith/vim-indent-object'
"""""""""""""""""""""""""""""""""""""""""""""""""""" Buffers """"""""""""""""""""""""""""""""""""""""""""""""""""""""""
map daf j<action>(MethodUp)<CR>jdai

**Comment by ronnac** [comment]
Actually, if I use nmap iso. map, I get the desired beviour.  You can close the issue.
-------- Original message --------From: TheBlob42 ***@***.***> Date: 05/12/22  11:03  (GMT+01:00) To: TheBlob42/idea-which-key ***@***.***> Cc: Nick Römer ***@***.***>, Author ***@***.***> Subject: Re: [TheBlob42/idea-which-key] which-key hinders execution of command (Issue #33) 

Thanks for the minimal example 👍

See this comment in the code. Which-key should not and does not intercept these type of "DIGRAPH" mappings (like d) at all because they are implemented differently and cause problems otherwise. But now there is a "regular" mapping as well so that the popup is still shown

The only fix I see so far is to implement a mechanism to disable the popup completely for a certain prefix (in this case d) to not run into this situation. Since to me it sounded like you disliked the popup for the d prefix anyway, I guess this would "solve" your problem

**Comment by TheBlob42** [comment]
Ah that makes sense, glad you solved it, will close the issue :+1:
