### ISSUE TITLE
feature request: set nowhich-key

### ISSUE THREAD

**Issue by ronnac** [TheBlob42/idea-which-key#34]
I would like to be able to toggle which-key on and off using a keyboard shortcut.

**Comment by TheBlob42** [comment]
Sorry for the long wait, I currently use the time I have on #32 
Will look into this afterwards, but from my gut feeling this should not be a big problem to implement :thinking:

**Comment by TheBlob42** [comment]
I have implemented the feature in 0ffd289fd3b331ab9fc99f4589dd5ea13772e657 on the `develop` branch. You can already build it locally for testing.

**Comment by TheBlob42** [comment]
Version `0.8.0` has been released on Github.
On the marketplace it will take a little longer due to pre-checks by Jetbrains
