### ISSUE TITLE
Unable to invoke which key when backspace is leader

### ISSUE THREAD

**Issue by goldlil** [TheBlob42/idea-which-key#36]
When backspace is leader key eg ```nmap <BS>e <Action>(FileStructurePopup)``` which key is not invoked. When using enter ```<CR>``` it's also not working.

Intelij version 2022.3

**Comment by TheBlob42** [comment]
This is unfortunately one of the [known issues](https://github.com/TheBlob42/idea-which-key#special-prefixes) of the plugin

**Comment by goldlil** [comment]
This is very sad :(

**Comment by TheBlob42** [comment]
It is :( maybe we'll find a way at some point
