### ISSUE TITLE
Vim motions fg, Fg, tg, Tg, etc, make the which-key menu open.

### ISSUE THREAD

**Issue by jrahhali** [TheBlob42/idea-which-key#4]
**Observed Behaviour**
Consider the sentence:

    I ate a grasshopper.

If you use any of the motions fg, Fg, tg, Tg, etc to put your cursor on 'g' in `grasshopper`, the which-key menu will open.  I suspect this is because the 'g' key is being pressed.

**Expected Behaviour**
The which-key menu will not open.

**Comment by TheBlob42** [comment]
Hey @jrahhali thanks for reporting this bug. This is clearly not what should happen in this case. I will have a look into it :male_detective:

**Comment by TheBlob42** [comment]
I have fixed the issue in c1bc66acfd249ec9e1a817c0178889d5bb1178fd
With the next version `0.3` the fix will be released.
If you like you can test it beforehand by building and installing the plugin manually.

Thanks for pointing this out :+1:

**Comment by jrahhali** [comment]
I've built and installed the plugin manually like you suggested, and the bug looks like it's fixed.  Thanks.
