### ISSUE TITLE
More sorting options, please

### ISSUE THREAD

**Issue by struckmb** [TheBlob42/idea-which-key#42]
It would be nice to add more sorting options:

Currently the "by_key" option is case sensitive (at least on my linux machine). Please add a case insensitive version.
Also a "by_key_prefix_last" would be a nice addition to the list. (That's the order of folke/which-key.nvim I'm used to.)

You should add to the description, that changing the sorting order needs a restart to have effect.

**Comment by TheBlob42** [comment]
Should not be a big problem in general :+1:  
I am currently on vacation so this might take a little longer for me to have a look into it

**Comment by TheBlob42** [comment]
You can already test the new options on the `develop` branch (need to build the plugin locally). Will do some testing and adapt the README before releasing the new additions.

**Comment by TheBlob42** [comment]
I just found a bug which was the reason why the sort order needed a restart to have an effect, will fix this to match the other options.

Also it seems to me that `:source ~/.ideavimrc` does not work anymore (at least for me), but one can use `:action IdeaVim.ReloadVimRc.reload` (or the button offered by Intellij). Will adapt the README about this.

**Comment by TheBlob42** [comment]
All changes merged. You can already build the plugin locally if you wish. Otherwise the review by JetBrains takes up to two business days before the new version is available in the marketplace.

**Comment by struckmb** [comment]
Thanks for your work!
