### ISSUE TITLE
How could I map a key like <Tab>, <Ctrl-H> and so on?

### ISSUE THREAD

**Issue by ayachinene0100** [TheBlob42/idea-which-key#45]
I have some key mappings like:

```
let g:WhichKeyDesc_nextTab = "<tab> go to next tab"
map <Tab> <Action>(NextTab)
let g:WhichKeyDesc_previousTab = "<s-tab> go to previous tab"
map <S-Tab> <Action>(PreviousTab)
```
And in the pop up, the description is still "<Action>(NextTab)", "<Action>(PreviousTab)"

How could I map key like \<Tab\>, \<Shift-xxxxx\>, \<Ctrl-xxxx\> correctly?

**Comment by TheBlob42** [comment]
Unfortunately special key mappings are not possible, check here: 
https://github.com/TheBlob42/idea-which-key#known-issues

**Comment by ayachinene0100** [comment]
> Unfortunately special key mappings are not possible, check here: https://github.com/TheBlob42/idea-which-key#known-issues

Oh, sorry, I didn't saw the document carefully. Anyway, thank you for your reply, and it's still a really good plugin
