### ISSUE TITLE
Can not initiate which key with "<Space>w"

### ISSUE THREAD

**Issue by anrivera16** [TheBlob42/idea-which-key#46]
Can not initiate which key with "<Space>w" for some reason. 
Here is my .ideavimrc file. 
Sorry I am new to vim and learning.

```
" .ideavimrc is a configuration file for IdeaVim plugin. It uses
"   the same commands as the original .vimrc configuration.
" You can find a list of commands here: https://jb.gg/h38q75
" Find more examples here: https://jb.gg/share-ideavimrc
set which-key
set notimeout
let g:WhichKeyDesc_windows = "<Space>w Windows"
let g:WhichKey_ShowVimActions = "true"

"" -- Suggested options --
" Show a few lines of context around the cursor. Note that this makes the
" text scroll if you mouse-click near the start or end of the window.
set scrolloff=5

" Do incremental searching.
set incsearch

" Don't use Ex mode, use Q for formatting.
map Q gq

" --- Enable IdeaVim plugins https://jb.gg/ideavim-plugins

" Highlight copied text
Plug 'machakann/vim-highlightedyank'
" Commentary plugin
Plug 'tpope/vim-commentary'
Plug 'preservim/nerdtree'

"" -- Map IDE actions to IdeaVim -- https://jb.gg/abva4t
"" Map \r to the Reformat Code action
"map \r <Action>(ReformatCode)

"" Map <leader>d to start debug
"map <leader>d <Action>(Debug)

"" Map \b to toggle the breakpoint on the current line
"map \b <Action>(ToggleLineBreakpoint)
```

**Comment by TheBlob42** [comment]
I am not sure I get your question correctly so please help me out :slightly_smiling_face: 

When you just press `w` VIM just jumps a word forward, so the plugin should not show anything there.
I see that you have configured a description for `<Space>w`, but your configuration does not contain any mapping for this key combination. If you for example add the following mappings you should see something when pressing space:

```vim
nnoremap <Space>wv :vertical splitv<CR>
nnoremap <Space>ws :split<CR>
nnoremap <Space>wd :close<CR>
" etc.
```

> In general: WhichKey does **not** set any mappings for you

Also not that lines starting with a `"` are considered comments, so they are not active (for example the `<leader>d` mapping close to the end of your configuration file)

If you want some inspiration or an easy "out of the box" setup for everything I can recommend the [intellimacs](https://github.com/MarcoIeni/intellimacs) project 

I hope this helps you a little bit already on your VIM learning journey

**Comment by anrivera16** [comment]
That is my misunderstanding. Thank you @TheBlob42 for the example. Will start customizing my menu.
