### ISSUE TITLE
Support for which key ignore

### ISSUE THREAD

**Issue by sosa-daniel** [TheBlob42/idea-which-key#47]
Can we have a way to hide a mapping from the menu like in vim-which-key?

**Comment by TheBlob42** [comment]
It works by setting an empty description, see [here](https://github.com/TheBlob42/idea-which-key#descriptions) (you have to scroll down a little)
![image](https://github.com/TheBlob42/idea-which-key/assets/6849129/1620ddc2-0c07-4d6a-be04-b7e4c05c64f6)

**Comment by sosa-daniel** [comment]
> It works by setting an empty description, see [here](https://github.com/TheBlob42/idea-which-key#descriptions) (you have to scroll down a little) ![image](https://private-user-images.githubusercontent.com/6849129/288289181-1620ddc2-0c07-4d6a-be04-b7e4c05c64f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzYzMTcsIm5iZiI6MTcwMTg3NjAxNywicGF0aCI6Ii82ODQ5MTI5LzI4ODI4OTE4MS0xNjIwZGRjMi0wYzA3LTRkNmEtYmUwNC1iN2U0YzA1YzY0ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTUyMDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMyZTQ3YjJhNDEzMDA3NDFjNjc0NDdmZGVjYjU1OTZkNjAxNWZmMDVhOTliOWQ5MWE0YTU1MDYyNTE3Y2JjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XJrDgyusx0JGGiwtgzhZMy46PUdAjG7Q7BDcHKth2kk)

That worked perfectly. Thank you!
