### ISSUE TITLE
Question: Transient state menus

### ISSUE THREAD

**Issue by jrahhali** [TheBlob42/idea-which-key#5]
Hi there.  I am wondering if is is possible for the which-key plugin to support something equivalent to Spacemac's [transient state menus](https://develop.spacemacs.org/doc/DOCUMENTATION.html#transient-states).

Here is an image from the Spacemacs documentation demonstrating a transient state in the editor:
![image](https://user-images.githubusercontent.com/3344066/110719498-55aea400-81e3-11eb-9bbb-04649878aa21.png)

The idea is, a user could enter `<leader> z x`to enter the a 'zoom' state.  From this state, the user could keep pressing the `+` or `-` buttons to zoom in and out, without having to enter the entire key mneumonic again, and the which-key menu remains open until the user escapes from it.

Is this functionality in the realm of possibility for this plugin?

**Comment by TheBlob42** [comment]
Hey @jrahhali I know about the transient state menus of Spacemacs and they are a really cool feature, but I guess this is out of the scope for the IDEA Which-Key plugin. This plugins only purpose is to display the available bindings in the editor not to let the user create new ones.

A "transient" plugin/extension would need to manage the repeatable keybindings as well as to give the user a way to customize them to their liking and it would probably need a different approach to address this topic. I think it would make more sense to create a separate project for this similar to the [transient](https://github.com/magit/transient) and [hydra](https://github.com/abo-abo/hydra) packages for emacs (which Spacemacs is probably using for its implementation). 

Never the less I think it would be super cool if one would implement such a feature to give as yet another way to improve our Intellij usage :slightly_smiling_face: _maaaaaybe_ if I have some more spare time I'll have a look into this, but don't take this as a promise :joy:

**Comment by jrahhali** [comment]
Thanks for sharing your thoughts on it.

**Comment by TheBlob42** [comment]
No problem :slightly_smiling_face: 
If I ever have some more thoughts, ideas or some code examples regarding the "transient state", I will message you here.
