### ISSUE TITLE
Which-Key is broken with latest IdeaVim EAP

### ISSUE THREAD

**Issue by lippfi** [TheBlob42/idea-which-key#56]
We've undertaken a significant refactoring of the KeyHandler to support the new Fleet IDE. Currently, IdeaVim is undergoing active changes to accommodate Fleet, and there may be additional issues in the near future. 
However, I plan to submit PRs to ensure that Which-Key remains operational. Unfortunately, it won't work in EAPs; I apologize for this inconvenience.

**Comment by TheBlob42** [comment]
Fixed version `0.10.1` is available via the Jetbrains marketplace and should fix the issues.
