### ISSUE TITLE
`IdeaVim 2.10.0-eap.3 throw NoSuchMethodError:com.maddyhome.idea.vim.command.MappingMode

### ISSUE THREAD

**Issue by CCCC-L** [TheBlob42/idea-which-key#57]
use `which-key 0.10.0` and `IdeaVim 2.10.0-eap.3` throw `java.lang.NoSuchMethodError: 'com.maddyhome.idea.vim.command.MappingMode com.maddyhome.idea.vim.command.MappingState.getMappingMode()'
` exception 

[stacktrace.txt](https://github.com/TheBlob42/idea-which-key/files/14497053/stacktrace.txt)

**Comment by lippfi** [comment]
Please see https://github.com/TheBlob42/idea-which-key/issues/56

**Comment by CCCC-L** [comment]
Okay, I'll start with the old version.
