### ISSUE TITLE
Which-key is popping up on insert mode

### ISSUE THREAD

**Issue by somtooo** [TheBlob42/idea-which-key#60]
On my mac i have which-key 0.9 and on insert mode it dosent pop when i use space(its my leader key) but on my pc(linux)  using the latest which-key verison it pops up on insert mode when i use space. Is there a way to disable this behaviour?

**Comment by somtooo** [comment]
OK fixed it by downgrading which-key back to 0.9 but it wasn't compatible with Ideavim 2.10.1 so I downgraded that to 2.7.5 and which-key does not pop up when I am in insert mode. 

Intellij version - 2023.3.5

Yeah,  something isn't right when using the latest version of everything.

**Comment by TheBlob42** [comment]
Version `0.10.1` of the WhichKey is available via the official Jetbrains marketplace. This should fix the issue. Therefore I'm closing this.
