### ISSUE TITLE
[BUG] `<Bslash>` does not show description

### ISSUE THREAD

**Issue by midrare** [TheBlob42/idea-which-key#61]
**To reproduce**

 1. Put in `.ideavim`
  ```vim
  let g:WhichKeyDesc_file_tree_focus = "<Bslash>f file tree"
  nmap <Bslash>f :NERDTreeFocus<CR>
  ```
 2. Press `\`
 3. Observe that the `g:WhichKeyDesc` description is not shown. Expected: "file tree" is shown next to the keybind

![Screenshot 2024-04-07 125949](https://github.com/TheBlob42/idea-which-key/assets/59168253/f27e402a-bb03-4d52-9d85-acec825e42c6)

---

**Notes**

For some reason, using `<Bslash>` as `mapleader` works fine.
```vim
set mapleader = "<Bslash>"

let g:WhichKeyDesc_file_tree_focus = "<leader>f file tree"
nmap <leader>f :NERDTreeFocus<CR>
```
![Screenshot 2024-04-07 130026](https://github.com/TheBlob42/idea-which-key/assets/59168253/f688399c-fda8-489e-b479-d85d0fea48d9)

**Comment by TheBlob42** [comment]
Thanks for the bug report.
I implemented a fix on the `develop` branch. Would be great if you could check if that fixes all your cases :slightly_smiling_face:

**Comment by TheBlob42** [comment]
Sorry for the long wait. The release is on its way (you can already manually install the latest version `0.10.2`)
