### ISSUE TITLE
gg pops up which-key modal

### ISSUE THREAD

**Issue by leonormes** [TheBlob42/idea-which-key#62]
When I us the gg to goto top of file, the which-key modal pops up and I have to dismiss it. 
If I press just g the modal comes up with the options for vim as I have `let g:WhichKey_ShowVimActions = "true"` set. It is like it is responding to one g press every time and not catching that I am double tapping g!

```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
  AceJump (3.8.19)
  IdeaVIM (2.11.0-eap.2)
  org.jetbrains.IdeaVim-EasyMotion (1.12)
  eu.theblob42.idea.whichkey (0.10.1)
  io.github.mishkun.ideavimsneak (1.2.0)
```
and 
```
set which-key
set notimeout
let g:WhichKeyDesc_leader = "<leader> Leader key"
let g:WhichKey_CommandColor = "#41ead4"
let g:WhichKey_FontFamily = "JetBrains Mono"
let g:WhichKey_FontSize = 16
let g:WhichKey_KeyColor = "#09ff00"
let g:WhichKey_PrefixColor = "#f335b2"
let g:WhichKey_ShowVimActions = "true"
let g:WhichKey_SortCaseSensitive = "false"
let mapleader = " "
```

**Comment by TheBlob42** [comment]
Can you please check with a "non EAP" version (e.g. `2.10.2`) of IdeaVim if the problem remains?

**Comment by leonormes** [comment]
Thanks @TheBlob42 , I tried that and the problem has gone away!

**Comment by TheBlob42** [comment]
@lippfi do you have any insights on what has changed in the newest EPA version that could cause this issue? :thinking:

**Comment by leonormes** [comment]
I am not sure if this is related but now, when I do <leader> the for instance x to get to a sub menu but then hit escape the x gets sent to the buffer and some text is deleted! I have deleted as much as I can and have a minimal ideavimrc but 🤷 . It could well be something in my env rather than which-key ideavim as I have removed most setting. I will try from fresh and see if it stops

**Comment by TheBlob42** [comment]
Have you tried setting the [ProcessUnknownMappings](https://github.com/TheBlob42/idea-which-key?tab=readme-ov-file#on-unknown-mapping) option to `false`? :thinking:

**Comment by leonormes** [comment]
I just tried it now. It did not make a difference. I have removed all plugins, set minimal ideavimrc and tried to remove as much external influence as I can, and it is doing it still. I must be something with my env as it is such an obvious error, you and others would see it happen. 🤔 
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Leon Ormes
Subscription is active until December 6, 2024.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 5000M
Cores: 8
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  terminal.new.ui=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  nl.dirkgroot.structurizr-dsl-plugin (0.3.5)
  IdeaVIM (2.10.2)
  eu.theblob42.idea.whichkey (0.10.1)
Kotlin: 241.14494.240-IJ

**Comment by TheBlob42** [comment]
Can you post your "minimal" `ideavimrc`? I don't see how your environment should be the reason here and would suspect that it is something with the configuration.

**Comment by leonormes** [comment]
I have removed everything except the NerdTree
```
let g:WhichKey_ProcessUnknownMappings = "false"
let mapleader = " "
set which-key
set notimeout
set nerdtree
let g:WhichKeyDesc_nerdtree_prefix = "<leader>x NerdTree"
let g:WhichKeyDesc_nerdtree_toggle = "<leader>xx Toggle NerdTree"
map <leader>xx :NERDTreeToggle<CR>
let g:WhichKeyDesc_nerdtree_focus = "<leader>xf Focus NerdTree"
map <leader>xf :NERDTreeFocus<CR>
```

**Comment by TheBlob42** [comment]
So I reread your question and now I see that I missed an important point: You aborted the mapping with a special key (here `<escape>`). In this case this is unfortunately one of the [known issues](https://github.com/TheBlob42/idea-which-key?tab=readme-ov-file#special-prefixes) and a limitation of the plugin that I could not find a way around so far (help is very welcome :wink:)

If you abort with another key (e.g. `a` in your example) the `g:WhichKey_ProcessUnknownMappings` option should work, the popup gets dismissed and no commands are executed.

**Comment by leonormes** [comment]
Thank you! I did not look there as I assumed I had always been doing it. Hitting escape to reset is so natural. Ok, so I just need to train myself to hit a non special key that has not command and it will exit the modal. 👍 
As a side note, your work is great and I use the mappings it enables to do everything I can in Intellij. So thank you :)
Do I close the issue or you?

**Comment by TheBlob42** [comment]
Yeah it is very natural and I would really like to "fix" this issue in general, but so far I had no luck.
Glad that I could help you out and thanks for the kind words :slightly_smiling_face: 
I will close the issue now.
