### ISSUE TITLE
The prompt box flashes

### ISSUE THREAD

**Issue by lamb007** [TheBlob42/idea-which-key#67]
### OS

ubuntu22.04 LTS

x11

## versions

clion2024.1 and clion2023.3 has same problem

which-key version: The latest version

### GPU

nvidia4060

## description

When using x11, when I press my leader-key, the prompt box at the bottom of the IDE keeps flashing, the interval is about half a second, and several times the layer of the prompt box is under the layer of the IDE
When I switched to wayland, there was no such problem, but the compatibility of other software in wayland was too poor
When I use it under windows, there is no such problem, so I think it may be an issue with x11 and nvidia gpu under linux (or something else)
I know it's hard for you to give me a solution to my uncommon problem. So I'd like to get some advice from you. If you develop on a linux platform, can you recommend a linux platform other than ubuntu (x11) that can use plug-ins normally?

thank you for taking the time!

**Comment by TheBlob42** [comment]
This is a very specific problem you got there :sweat_smile: 
I actually work exclusively on Linux and never ran into such a problem neither on my personal computer (Pop!_OS with X11) nor my work machine (Ubuntu also with X11). For comparison I only use Intellij, so maybe you could check if the issue appears there as well (Intellij Community is free to use). Also check your IdeaVim version. Other than this I have no idea so far :thinking:
