### ISSUE TITLE
Showing which-key in Intellj IDE does not work

### ISSUE THREAD

**Issue by paulWyszynski** [TheBlob42/idea-which-key#69]
Hey,
I've added the plugin from marketplace and added this to my vimrc:

```
set which-key                             -- show keybindings the vim way
set notimeout                             -- no timeout for which-key
```

But unfortunately the which-key popup does not appear. Whats the key combo for that? <Space> or <Space>w???

**Comment by TheBlob42** [comment]
See also https://github.com/TheBlob42/idea-which-key/issues/46
