### ISSUE TITLE
<tab> directory not working

### ISSUE THREAD

**Issue by Elyviere** [TheBlob42/idea-which-key#72]
How to reproduce:
Add the following to .ideavimrc

```
let g:WhichKeyDesc_tab = "<leader><tab> +tabs"
nmap <leader><tab>] <Action>(NextTab)
let g:WhichKeyDesc_tab_next = "<leader><tab>] Next Tab"
```

Press \<leader\>\<tab\>

What is expected: WhichKey plugin shows ] as the next available command

What actually happens: Whichkey closes when pressing \<tab\>

Bonus error: Whichkey capitalises \<tab\> into \<Tab\>. Space works the same, <space> becomes <Space>
![image](https://github.com/user-attachments/assets/c6246943-fdd5-4f9d-bedf-01c94ef804a3)

**Comment by TheBlob42** [comment]
This is a known issue and mentioned in the [Known Issues](https://github.com/TheBlob42/idea-which-key?tab=readme-ov-file#special-prefixes) section of the `README` file. It affects all special keys. I personally have given up the research on how to make this work, but I am happy to accept contributions in this regard.

The bonus error is not an error but just the String representation of the `tab` key. Some other keys (like space) are specifically replaced to match this style (see [here](https://github.com/TheBlob42/idea-which-key/blob/main/src/main/kotlin/eu/theblob42/idea/whichkey/config/MappingConfig.kt#L368)), but tab is returned by IdeaVim this way.
