### ISSUE TITLE
plugins crash

### ISSUE THREAD

**Issue by shishi** [TheBlob42/idea-which-key#73]
ideavim 2.15.3
which-key 0.10.2

my config about which-key

```
set which-key

" plugins/which-key
set notimeout
let g:WhichKey_ShowVimActions = "false"
```

reproduce to press `<C-w>` or other combination.

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'eu.theblob42.idea.whichkey.WhichKeyShortcutKeyAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: eu.theblob42.idea.whichkey]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by TheBlob42** [comment]
What is the version of your IDE?

**Comment by shishi** [comment]
I'm using Rubymine 2024.1.6

**Comment by TheBlob42** [comment]
Hmm that should not crash the plugin to my understanding (from [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/18697727524754-Deprecation-warning-with-ActionUpdateThread)). I can have a look to fix this deprecation warning and find out what this is all about, but I'm a little short on time currently :grimacing:

**Comment by shishi** [comment]
OK 😢, I'm new to RubyMine, but I've used which-key from the original Emacs version and in Vim for years. Thank you for creating this plugin.

**Comment by TheBlob42** [comment]
So the weird thing for me is that even running with the latest IdeaVim `2.16.0` and WhichKey `0.10.2` I don't have any problems or crashes. But I am **not** using RubyMine but Intellij instead, so maybe there is a some difference.

I have added the missing override mentioned in the error message, but as this does not make any difference for me I am hesitate to release a new version with it yet. Could you please test this for me?

Download the test build jar file here: https://github.com/TheBlob42/idea-which-key/releases/tag/0.10.3-test
Install it manually using the instructions provided [here](https://github.com/TheBlob42/idea-which-key/releases/tag/0.10.3-test)

Let me know if this resolves the issue for you. If so I would draft a proper version for releasing

**Comment by shishi** [comment]
Sure. I will test it in some days

**Comment by shishi** [comment]
I have confirmed to work test version with RubyMine 2024.2.0.1, IdeaVim 2.16.0, remote development in devcontainer in Mac M1. Thanks!

**Comment by TheBlob42** [comment]
Nice, then I will prepare a new release :+1:

**Comment by TheBlob42** [comment]
Version [0.10.3](https://plugins.jetbrains.com/plugin/15976-which-key/edit/versions/stable/593529) is now available via the Jetbrains marketplace. This should fix the issue
