### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by SelaOZ** [TheBlob42/idea-which-key#77]
I did this: Activate the plugin in your .ideavimrc file with `set which-key`

But nothing happens no matter what key I press, how can I view the window with all the commands like shown in the image of the plugin? 

Is there a specific key or shortcut to view that screen? 
I don't see anything specific in the docs.

**Comment by TheBlob42** [comment]
Just to be sure have you read this part of the README file? (right at the start underneath the GIF)

> Which-Key only displays available keybindings, it will not set them for you (https://github.com/TheBlob42/idea-which-key/issues/44, https://github.com/TheBlob42/idea-which-key/issues/46)  
> For a "complete" setup you might have a look at [intellimacs](https://github.com/MarcoIeni/intellimacs) (which was used for the GIF above)

If this is not the problem here, please share your `.ideavimrc` file here for further investigation

**Comment by SelaOZ** [comment]
It's the default:

```
" .ideavimrc is a configuration file for IdeaVim plugin. It uses
"   the same commands as the original .vimrc configuration.
" You can find a list of commands here: https://jb.gg/h38q75
" Find more examples here: https://jb.gg/share-ideavimrc


"" -- Suggested options --
" Show a few lines of context around the cursor. Note that this makes the
" text scroll if you mouse-click near the start or end of the window.
set scrolloff=5

" Do incremental searching.
set incsearch

" Don't use Ex mode, use Q for formatting.
map Q gq

" --- Enable IdeaVim plugins https://jb.gg/ideavim-plugins

" Highlight copied text
Plug 'machakann/vim-highlightedyank'
" Commentary plugin
Plug 'tpope/vim-commentary'


"" -- Map IDE actions to IdeaVim -- https://jb.gg/abva4t
"" Map \r to the Reformat Code action
"map \r <Action>(ReformatCode)

"" Map <leader>d to start debug
"map <leader>d <Action>(Debug)

"" Map \b to toggle the breakpoint on the current line
"map \b <Action>(ToggleLineBreakpoint)

set which-key
set timeoutlen=5000
```

I don't want to set keybindings, I want to view the available vim commands and I use the default, I want to view the screen in the plugin's image with all of the available commands:
![image](https://github.com/user-attachments/assets/94b6350b-1a60-4ce8-a324-79b8dbb868f0)

**Comment by TheBlob42** [comment]
The commands in the screenshot are NOT the defaults. These are all manually set keybindings (in this case using the [intellimacs](https://github.com/MarcoIeni/intellimacs) project). Have a read [here](https://github.com/TheBlob42/idea-which-key/issues/44#issuecomment-1788472425) or check this issue [here](https://github.com/TheBlob42/idea-which-key/issues/46).

The popup you are seeing is for the `tpope/vim-commentary` plugin which you have activated. This plugin sets new keybindings (e.g. `gcc`) which are then shown by which-key. The keybindings from the screenshot (e.g. `<Space>w-`) are not set by default. But if you create a keybinding for it, it will be shown.
