### ISSUE TITLE
Load Context

### ISSUE THREAD

**Issue by sidouglas** [TheBlob42/idea-which-key#78]
Forgive me — I'm not a Java Dev. I am looking for a way to perform context operations:

```
Tools > Tasks & Contexts > Save Context
Tools > Tasks & Contexts > Load Context
Tools > Tasks & Contexts > Clear Context
```
I couldn't see a way to do it - e.g `nmap <leader>bc <Action>(LoadContext)`  (where do you find these commands?)

**Comment by TheBlob42** [comment]
You can view all the available actions via `:actionlist<CR>` (typing colon followed by the word "actionlist" followed by pressing enter) or check out this list [here](https://gist.github.com/zchee/9c78f91cc5ad771c1f5d) (now idea how up to date it is).

You can map actions via `:action <name of the action><CR>`, so in your example it should work like this:
```vim
nmap <leader>bc :action context.load<CR>
```

**Comment by sidouglas** [comment]
Wonderful — thank you!
