### ISSUE TITLE
Is the popup delay configurable?

### ISSUE THREAD

**Issue by stephenkraemer** [TheBlob42/idea-which-key#8]
Hi,
thanks a lot for this great plugin! I am not sure whether I have overlooked it: is there a way to configure the popup delay? If not, I would be grateful if you would consider making this a feature whenever you have the time :)
Cheers,
Stephen

**Comment by TheBlob42** [comment]
Hey Stephen, first of all thank you :heart:  

Actually it is already on my TODO list for this project and should not really be a big issue to implement. If I have some more time in the next days/weeks I will have a look into this :+1:

**Comment by TheBlob42** [comment]
I have implemented the feature on the `develop` branch. You can check it out and build it locally to test it. There are a few things I would like to implement as well before preparing a new release.

See this commit: 18b78c9781c1bb344761060eb0ea1ece999ebc00

Basically you can configure the delay (in ms) via the `g:WhichKey_DefaultDelay` variable.

**Comment by stephenkraemer** [comment]
That was fast :) Thanks a lot!

**Comment by TheBlob42** [comment]
Hey just wanted to let you know that version `0.4` is released and contains the option to configure the popup delay.
Therefore I will close this ticket, but please write me if you have any other questions :slightly_smiling_face:
