### ISSUE TITLE
When typing fast Popup remains open 

### ISSUE THREAD

**Issue by jigargosar** [TheBlob42/idea-which-key#80]
```
set notimeout
" set timeout-len=5000
let g:WhichKey_ProcessUnknownMappings = "false"
let g:WhichKey_DefaultDelay = 100
set which-key
map <leader><tab> <C-6>
```

sometimes I type the commands really fast. Even after reducing default delay, popup still remains open. 
I have to set it to zero to ensure that popup closes after valid keys are pressed.

Is this a known issue? I am ok with popup appearing bit late, but ideally it shouldn't appear once any mapping has been typed and executed.

Thanks for the great work.

**Comment by TheBlob42** [comment]
This is not a general issue, but one with "special keys" like `<tab>` in your example, see [here](https://github.com/TheBlob42/idea-which-key?tab=readme-ov-file#special-prefixes) for more information. Test it with another mapping that contains only letters or numbers and you should not experience the issue

**Comment by jigargosar** [comment]
Thanks, just verified that it a known issue for any special key combo including <tab>.
FYI: I have to keep the delay at 0 when I have even one mapping with special keys.
Otherwise having popup remain on screen, is very jarring. More so than flickering.

Thanks for the reply, and all the good work.
